/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'quickstart',
    {
      type: 'category',
      label: 'Installation',
      link: {
        type: 'generated-index',
        description: 'Step-by-step installation guides for a range of programming languages and frameworks.',
      },
      items: [
        'installation/cdn',
        {
          type: 'category',
          label: 'Documentation sites',
          items: [
            'installation/antora',
            'installation/astro',
            'installation/docusaurus',
            'installation/fumadocs',
            'installation/hugo',
            'installation/jekyll',
            'installation/madcap-flare',
            'installation/mkdocs',
            'installation/nextra',
            'installation/paligo',
            'installation/sphinx',
            'installation/starlight',
            'installation/vitepress',
            'installation/vuepress',
          ],
        },
        {
          type: 'category',
          label: 'JavaScript & React apps',
          items: [
            'installation/npm',
            'installation/react',
            'installation/nextjs',
            'installation/vue',
            'installation/gatsby',
          ],
        },
        {
          type: 'category',
          label: 'Website builders',
          items: [
            'installation/webflow',
            'installation/wordpress',
            'installation/learndash',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Customization',
      link: {
        type: 'generated-index',
      },
      items: [
        {type: 'autogenerated', dirName: 'customization'},
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      link: {
        type: 'generated-index',
      },
      items: [
        {type: 'autogenerated', dirName: 'integrations'},
      ],
    },
    {
      type: 'category',
      label: 'Administration',
      link: {
        type: 'generated-index',
      },
      items: [
        {type: 'autogenerated', dirName: 'administration'},
      ],
    },
    'support',
  ],
};

module.exports = sidebars;
